/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.spring.pet;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

@SpringBootApplication(scanBasePackages = {"gradle.spring.pet.main"})
@EntityScan(basePackages = {"entities"})
@EnableJpaRepositories(basePackages =
{"repositories"})
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
